name: Main

on:
  pull_request:
    branches:
      - main
      - main4x
  push:
    branches:
      - main
      - main4x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn test
      - run: yarn build
